# Generated by Django 4.1.3 on 2022-11-10 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
    ]
