# Generated by Django 3.2.7 on 2022-05-23 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_rename_reporter_article_reporter_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='reporter_name',
            new_name='reporter',
        ),
    ]
