# Generated by Django 3.2.7 on 2022-05-27 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='drink_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='drink',
            name='drink_url',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
