# Generated by Django 4.1.3 on 2022-11-19 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='completion',
        ),
    ]
