# Generated by Django 4.1.3 on 2022-11-26 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_alter_todo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='completed_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_date',
            field=models.DateField(blank=True),
        ),
    ]
