# Generated by Django 4.1.3 on 2022-11-26 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_alter_todo_completed_date_alter_todo_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
