# Generated by Django 4.1.3 on 2022-11-26 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_alter_todo_completed_date_alter_todo_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='completed_date',
            new_name='completed_radio',
        ),
    ]
