# Generated by Django 4.1.3 on 2022-11-26 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0006_remove_todo_completed_radio'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='completed_todo',
            field=models.BooleanField(default='True'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_date',
            field=models.DateField(),
        ),
    ]
