# Generated by Django 4.1.3 on 2022-11-26 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0007_todo_completed_todo_alter_todo_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='completed_todo',
            field=models.BooleanField(),
        ),
    ]
