# Generated by Django 4.1.3 on 2022-11-29 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0008_alter_todo_completed_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='completed_todo',
            field=models.BooleanField(default=False),
        ),
    ]
