# Generated by Django 4.1.3 on 2022-11-30 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0009_alter_todo_completed_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='incomplete_todo',
            field=models.BooleanField(default=False),
        ),
    ]
