# Generated by Django 3.2.7 on 2022-05-22 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='reporter_name',
            new_name='reporter',
        ),
    ]
