# Generated by Django 4.1.3 on 2022-11-12 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='short',
            old_name='urls',
            new_name='url',
        ),
    ]
