# Generated by Django 4.1.3 on 2022-11-22 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo_item',
            name='title',
            field=models.TextField(default='chore', max_length=200),
        ),
        migrations.AlterField(
            model_name='todo_item',
            name='text',
            field=models.TextField(max_length=200),
        ),
    ]
