# Generated by Django 4.1.3 on 2022-11-24 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_lists', '0003_todo_item_date_started'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo_item',
            name='date_started',
        ),
    ]
