# Generated by Django 4.1.3 on 2022-11-24 04:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_lists', '0004_remove_todo_item_date_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo_item',
            name='date_started',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='todo_item',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
