# Generated by Django 4.1.3 on 2022-11-05 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0002_todoitem_todolist_delete_blog_todoitem_to_do_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='to_do_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='to_do_app.todolist'),
        ),
    ]
