# Generated by Django 4.0.6 on 2022-08-04 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField(blank=True)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('length_of_set', models.CharField(blank=True, max_length=200)),
                ('gig_or_rehearsal', models.CharField(blank=True, choices=[('gig', 'Gig'), ('rehearsal', 'Rehearsal')], default='Gig', max_length=9)),
                ('rate_of_pay', models.IntegerField(blank=True)),
                ('lodging', models.CharField(blank=True, max_length=200)),
                ('venue_contact', models.CharField(blank=True, max_length=200)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
