# Generated by Django 4.1.2 on 2022-11-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('many_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team_name',
            field=models.ManyToManyField(null=True, to='many_app.team'),
        ),
    ]
