# Generated by Django 4.1.1 on 2022-11-08 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_input', models.CharField(max_length=9999)),
                ('url_output', models.CharField(max_length=13)),
            ],
        ),
    ]
