# Generated by Django 4.1.3 on 2022-11-11 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='url_input',
            new_name='long_url',
        ),
        migrations.RenameField(
            model_name='url',
            old_name='url_output',
            new_name='short_url',
        ),
    ]
