# imports random module
import random

# initialize variable 'x' to hold a random number between 1 and 10 generated by random.randint() function
x = random.randint(1,10)

# initialize variable 'guesses' that will increment up with each guess. the starting value is 0 and once it gets to 10 the loop will end.
guesses = 0

# print(x)
# initialize a loop that will run until the user has guessed 10 times.
while True:
    
    #initialize variable 'guess' that will store the value of the user's guess.
    guess = input("\nGuess a number between one and ten: ")
    # convert the 'guess' from a string to an integer.
    guess = int(guess)

    # compare 'guess' to 'x', the random number. If they are NOT the same, display 'Try Again' and the code will begin again. Increments 'guesses' by 1.
    if guess != x:
        print("\nTry again.")
        guesses += 1
    
    
    # compare 'guess' to 'x', the random number. If they are the same, display 'You win!', and end the loop.
    elif guess == x:
        print(f"\nYou win! You guessed {guesses} times.")
        break
    
    




