# Generated by Django 4.1.3 on 2022-11-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='created_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='description',
            field=models.TextField(default=1987, max_length=500),
            preserve_default=False,
        ),
    ]
