# Generated by Django 4.1.3 on 2022-11-08 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0002_alter_todoitem_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
