# Generated by Django 4.1.3 on 2022-11-10 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0004_rename_todoitem_todoitems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TodoItems',
            new_name='TodoItem',
        ),
    ]
