# Generated by Django 4.1.3 on 2022-11-11 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0005_rename_todoitems_todoitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={},
        ),
    ]
