# Generated by Django 4.1.4 on 2022-12-29 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_game_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='attack_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('attack', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='defense_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('defense', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='item',
        ),
    ]
