# Generated by Django 4.1.4 on 2022-12-29 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_game_app', '0002_attack_item_defense_item_delete_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='attack_items',
            field=models.ManyToManyField(related_name='players', to='main_game_app.attack_item'),
        ),
        migrations.AddField(
            model_name='player',
            name='defense_items',
            field=models.ManyToManyField(related_name='players', to='main_game_app.defense_item'),
        ),
    ]
