# Generated by Django 4.1.4 on 2023-01-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_game_app', '0003_player_attack_items_player_defense_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('defense', models.IntegerField()),
                ('attack', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='attack_items',
        ),
        migrations.RemoveField(
            model_name='player',
            name='defense_items',
        ),
        migrations.DeleteModel(
            name='attack_item',
        ),
        migrations.DeleteModel(
            name='defense_item',
        ),
        migrations.AddField(
            model_name='player',
            name='items',
            field=models.ManyToManyField(related_name='players', to='main_game_app.item'),
        ),
    ]
