# Generated by Django 4.1.4 on 2023-01-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_game_app', '0007_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
