# Generated by Django 4.1.4 on 2023-01-16 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_game_app', '0008_alter_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
    ]
