# Generated by Django 4.1.4 on 2023-01-18 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_game_app', '0011_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='main_game_app/static/'),
        ),
    ]
