# Generated by Django 4.1.5 on 2023-01-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todolist_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
