# Generated by Django 4.1.2 on 2022-11-03 03:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_rename_pub_date_blog_updated_date_blog_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='completed_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='completed_task',
            field=models.BooleanField(default=False),
        ),
    ]
